---
# # Install pre-commit hooks via
# pre-commit install

default_langauge_version:
  python: python3

repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear"]
