language: python
dist: bionic

stages:
  - linting
  - test

cache:
  pip: true

before_install:
  - pip install 'poetry>=1.0.0b1'

install:
  - poetry install -v

script:
  - pytest --cov-report xml --cov-report term-missing --cov-append --cov cp2k_input_tools tests/

after_success:
  - codecov

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"

env:
  global:
  - secure: Sx49HS24CVL7IcjaNOEOm8dRT2nyrtmONvcl4Y6bzXbuHXr+DBAZf925bs1E2lD61Zyi4KRLWAMENGNXlP09aDR6JfECkJbcdCZMpOE6VaFBACalHJnFvpWf3n2lzayO2UCUEsjHUiBB6nIq2182K0yPSnnmurM4MvhAcx7kOaFuWcL9FaQ5B/CgWaRA9dpqxojt5KfBqGm0xOIb+bnuerhXiWM13sOrb/gHLzSYEYnW+hjH6nYftsKDCcc9V5bb7l5ggjfmcI/HVjO1wEAHlvwfK4F/4EJciO0WBssVaYeSrPZXEMMFJx/bZQJ+ddkgC4HCPESILo1h0uLG17QLqNXRxH7owNO9AGiNpvICSibP0nIYJSoFfAGtHbyIPt2g69g10aQGlsSyGqsEDGMuqcgdBXxuSmtkTa8lSlaYV9aZBSpxonsj1WOLhl/psgzlRA9ym4ybRHccVbSvPahqhppYwiYBIt8VnDp2eh1oeG3zghkbayO4XN2jNrTd0MeKJB9lK3oZe86DS3ZfOoeRkzPFAUcShyrNF+IQiVXCfDFkdRjbMe8zy89kcD1y0q8pfvV5CcgebxDC9jQCM6OGUIZPIJYllAx+8Gd6LtJ8lVi/FAE6X+tvc8YqXV/S87LaUAlSIVDNSBcMXSN9p3s2ThslpNN9BuAGk9WsDeuQLP0=
  - secure: ZoikwMqdmwDRzTnKQxqxlF0DGGtMnZMnFkrPo8pZABeI4Tu1XOfialsPh0AzSssAenFUuq+EBhibjWaydUANsDcl2umkxGDjDhEXQaFYd3/UIsvQMiTVWv9A82Iv4R29qS2csYLGN9A8tt0GfCSqA+49alzPwdHwqS/yR2YUiiROAXWDeUP9lveT0wTEATJcTQOMDIzbOVQGbe4dUPYyrCLi8y7lcZSsxHM/vvSep6RmQtq/p//K1t/SdzyusOdkoGPxy3U8dRQRicDVfLXuEmx7hS//Gabs3F6NQO+wRGwyfr1IvACfrbzciJGHUFURxu4kxwfxWB8UUJlgdelxlffUSDeQRbzi6X0KAVY6MMEwZGsX+fKGgzB/h70+LayiRpszXUur/oVqvTq6q5p5ozgyVlOTHDOqIeEA9XmazcBmXJQgtcAbP2VzThsvXRcGsbxMwuGBgBPSogMv4bH1GR4kdjXjwszJBeRyVKh5KBGAOZ1XYqkWjQ2iWF0iHyIZ+kBVi5PZQqeOEJri0M/6XJ/+GRHF8LdRycBuaXAkSyri43UwGa7z5j5lc/oiZDwX/rMdI7crJ6UeSOI82YahiuVzU3N4B+6rcszn36KyO2Uv5lcpKptERM/P/FL2yE5fw4/UyOtcZ1pDxlQ/YsOtusKIifvy/ViBGmJYg6nRJ6I=
