language: python
dist: bionic

stages:
  - linting
  - test

cache:
  pip: true

before_install:
  - pip install 'poetry>=1.0.0b1'

install:
  - poetry install -v

script:
  - pytest --cov-report xml --cov-report term-missing --cov-append --cov cp2k_input_tools tests/

after_success:
  - codecov

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
